services:
  app:
    container_name: app
    image: lc2020/projeto_cloud_lucac:v5
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY:-a5e6fda737aa4c22a9e80fb273aec1455a2bfc4854905ee0a2d5747b8272d6d5}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME:-projeto}
      DATABASE_USER: ${DATABASE_USER:-projeto}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-projeto} 
    depends_on:
      - db
    restart: always

  db:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-projeto}
      POSTGRES_USER: ${DATABASE_USER:-projeto}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-projeto} 
    ports: 
      - "5432:5432"
