version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your_secret_key  # Substitua pela sua chave secreta
      - DATABASE_URL=postgresql://postgres:senha@db:5432/database  # Configuração do banco de dados
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha  # Substitua pela senha desejada
    ports:
      - "5432:5432"
